package init

import (
	"fmt"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// HaloyConfig represents the haloy.yaml configuration
type HaloyConfig struct {
	Name   string         `yaml:"name"`
	Server string         `yaml:"server"`
	Image  *ImageConfig   `yaml:"image"`
	Port   string         `yaml:"port"`
	Env    []EnvVarConfig `yaml:"env,omitempty"`
}

// ImageConfig represents the image configuration in haloy.yaml
type ImageConfig struct {
	Repository  string       `yaml:"repository"`
	Build       bool         `yaml:"build"`
	BuildConfig *BuildConfig `yaml:"build_config,omitempty"`
}

// BuildConfig represents build configuration
type BuildConfig struct {
	Context    string `yaml:"context,omitempty"`
	Dockerfile string `yaml:"dockerfile,omitempty"`
}

// EnvVarConfig represents an environment variable in haloy.yaml
type EnvVarConfig struct {
	Name string         `yaml:"name"`
	From *FromReference `yaml:"from,omitempty"`
}

// FromReference represents a reference to an external value source
type FromReference struct {
	Env string `yaml:"env"`
}

// GenerateHaloyConfig creates a HaloyConfig for the given project
func GenerateHaloyConfig(projectDir string, framework Framework, server string, envVars []string) *HaloyConfig {
	// Derive app name from directory name
	appName := sanitizeAppName(filepath.Base(projectDir))

	config := &HaloyConfig{
		Name:   appName,
		Server: server,
		Port:   framework.DefaultPort(),
		Image: &ImageConfig{
			Repository: appName,
			Build:      true,
			BuildConfig: &BuildConfig{
				Context:    ".",
				Dockerfile: "Dockerfile",
			},
		},
	}

	// Add environment variables
	for _, varName := range envVars {
		config.Env = append(config.Env, EnvVarConfig{
			Name: varName,
			From: &FromReference{
				Env: varName,
			},
		})
	}

	return config
}

// MarshalYAML generates the YAML content for the haloy.yaml file
func (c *HaloyConfig) MarshalYAML() ([]byte, error) {
	return yaml.Marshal(c)
}

// MarshalYAMLWithComments generates YAML content with helpful comments
func (c *HaloyConfig) MarshalYAMLWithComments() ([]byte, error) {
	var sb strings.Builder

	sb.WriteString("# Haloy deployment configuration\n")
	sb.WriteString("# Generated by `haloy init`\n")
	sb.WriteString("# Documentation: https://haloy.dev/docs/configuration\n\n")

	// Name
	sb.WriteString(fmt.Sprintf("name: %s\n", c.Name))

	// Server
	sb.WriteString(fmt.Sprintf("server: %s\n", c.Server))

	// Image
	sb.WriteString("\nimage:\n")
	sb.WriteString(fmt.Sprintf("  repository: %s\n", c.Image.Repository))
	sb.WriteString(fmt.Sprintf("  build: %t\n", c.Image.Build))
	if c.Image.BuildConfig != nil {
		sb.WriteString("  build_config:\n")
		sb.WriteString(fmt.Sprintf("    context: %s\n", c.Image.BuildConfig.Context))
		sb.WriteString(fmt.Sprintf("    dockerfile: %s\n", c.Image.BuildConfig.Dockerfile))
	}

	// Port
	sb.WriteString(fmt.Sprintf("\nport: %s\n", c.Port))

	// Domains (commented out as placeholder)
	sb.WriteString("\n# Uncomment and configure your domain(s):\n")
	sb.WriteString("# domains:\n")
	sb.WriteString("#   - domain: example.com\n")
	sb.WriteString("#     aliases:\n")
	sb.WriteString("#       - www.example.com\n")
	sb.WriteString("#\n")
	sb.WriteString("# acme_email: admin@example.com\n")

	// Environment variables
	if len(c.Env) > 0 {
		sb.WriteString("\n# Environment variables (referenced from host environment)\n")
		sb.WriteString("# Make sure these are set in your deployment environment\n")
		sb.WriteString("env:\n")
		for _, env := range c.Env {
			sb.WriteString(fmt.Sprintf("  - name: %s\n", env.Name))
			if env.From != nil {
				sb.WriteString(fmt.Sprintf("    from:\n"))
				sb.WriteString(fmt.Sprintf("      env: %s\n", env.From.Env))
			}
		}
	} else {
		sb.WriteString("\n# Environment variables\n")
		sb.WriteString("# env:\n")
		sb.WriteString("#   - name: DATABASE_URL\n")
		sb.WriteString("#     from:\n")
		sb.WriteString("#       env: DATABASE_URL\n")
	}

	// Health check (commented out)
	sb.WriteString("\n# Health check path (uncomment if your app has a health endpoint)\n")
	sb.WriteString("# health_check_path: /health\n")

	return []byte(sb.String()), nil
}

// sanitizeAppName converts a directory name to a valid app name
func sanitizeAppName(name string) string {
	// Convert to lowercase
	name = strings.ToLower(name)

	// Replace spaces and underscores with hyphens
	name = strings.ReplaceAll(name, " ", "-")
	name = strings.ReplaceAll(name, "_", "-")

	// Remove any characters that aren't alphanumeric or hyphens
	var result strings.Builder
	for _, r := range name {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' {
			result.WriteRune(r)
		}
	}
	name = result.String()

	// Remove leading/trailing hyphens
	name = strings.Trim(name, "-")

	// Collapse multiple hyphens
	for strings.Contains(name, "--") {
		name = strings.ReplaceAll(name, "--", "-")
	}

	// If empty after sanitization, use a default
	if name == "" {
		name = "app"
	}

	return name
}
