package init

import (
	"strings"
	"testing"
)

func TestSanitizeAppName(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"my-app", "my-app"},
		{"My App", "my-app"},
		{"my_app", "my-app"},
		{"MyApp", "myapp"},
		{"my.app.name", "myappname"},
		{"my@app!", "myapp"},
		{"  spaced  ", "spaced"},
		{"-leading-hyphen", "leading-hyphen"},
		{"trailing-hyphen-", "trailing-hyphen"},
		{"multiple---hyphens", "multiple-hyphens"},
		{"123app", "123app"},
		{"app123", "app123"},
		{"", "app"},
		{"@#$%", "app"},
		{"UPPERCASE", "uppercase"},
		{"MixedCase-App_Name", "mixedcase-app-name"},
	}

	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			result := sanitizeAppName(tt.input)
			if result != tt.expected {
				t.Errorf("sanitizeAppName(%q) = %q, want %q", tt.input, result, tt.expected)
			}
		})
	}
}

func TestGenerateHaloyConfig(t *testing.T) {
	envVars := []string{"DATABASE_URL", "API_KEY", "REDIS_URL"}

	config := GenerateHaloyConfig("/path/to/my-project", FrameworkNextJS, "api.example.com", envVars)

	if config.Name != "my-project" {
		t.Errorf("Name = %v, want my-project", config.Name)
	}
	if config.Server != "api.example.com" {
		t.Errorf("Server = %v, want api.example.com", config.Server)
	}
	if config.Port != "3000" {
		t.Errorf("Port = %v, want 3000", config.Port)
	}
	if config.Image == nil {
		t.Fatal("Image should not be nil")
	}
	if config.Image.Repository != "my-project" {
		t.Errorf("Image.Repository = %v, want my-project", config.Image.Repository)
	}
	if !config.Image.Build {
		t.Error("Image.Build should be true")
	}
	if len(config.Env) != 3 {
		t.Errorf("len(Env) = %v, want 3", len(config.Env))
	}
}

func TestGenerateHaloyConfig_NoEnvVars(t *testing.T) {
	config := GenerateHaloyConfig("/path/to/app", FrameworkDjango, "server.com", nil)

	if config.Port != "8000" {
		t.Errorf("Port = %v, want 8000 for Django", config.Port)
	}
	if len(config.Env) != 0 {
		t.Errorf("len(Env) = %v, want 0", len(config.Env))
	}
}

func TestHaloyConfig_MarshalYAML(t *testing.T) {
	config := &HaloyConfig{
		Name:   "test-app",
		Server: "api.example.com",
		Port:   "3000",
		Image: &ImageConfig{
			Repository: "test-app",
			Build:      true,
			BuildConfig: &BuildConfig{
				Context:    ".",
				Dockerfile: "Dockerfile",
			},
		},
		Env: []EnvVarConfig{
			{Name: "DATABASE_URL", From: &FromReference{Env: "DATABASE_URL"}},
		},
	}

	data, err := config.MarshalYAML()
	if err != nil {
		t.Fatalf("MarshalYAML() error = %v", err)
	}

	yaml := string(data)

	if !strings.Contains(yaml, "name: test-app") {
		t.Error("YAML should contain 'name: test-app'")
	}
	if !strings.Contains(yaml, "server: api.example.com") {
		t.Error("YAML should contain 'server: api.example.com'")
	}
	if !strings.Contains(yaml, "build: true") {
		t.Error("YAML should contain 'build: true'")
	}
}

func TestHaloyConfig_MarshalYAMLWithComments(t *testing.T) {
	config := &HaloyConfig{
		Name:   "test-app",
		Server: "api.example.com",
		Port:   "3000",
		Image: &ImageConfig{
			Repository: "test-app",
			Build:      true,
			BuildConfig: &BuildConfig{
				Context:    ".",
				Dockerfile: "Dockerfile",
			},
		},
		Env: []EnvVarConfig{
			{Name: "DATABASE_URL", From: &FromReference{Env: "DATABASE_URL"}},
			{Name: "API_KEY", From: &FromReference{Env: "API_KEY"}},
		},
	}

	data, err := config.MarshalYAMLWithComments()
	if err != nil {
		t.Fatalf("MarshalYAMLWithComments() error = %v", err)
	}

	yaml := string(data)

	checks := []struct {
		name     string
		contains string
	}{
		{"header comment", "# Haloy deployment configuration"},
		{"generated comment", "Generated by `haloy init`"},
		{"name field", "name: test-app"},
		{"server field", "server: api.example.com"},
		{"image section", "image:"},
		{"repository", "repository: test-app"},
		{"build config", "build_config:"},
		{"port field", "port: 3000"},
		{"domains comment", "# Uncomment and configure your domain"},
		{"env section", "env:"},
		{"env var name", "- name: DATABASE_URL"},
		{"env var from", "from:"},
		{"health check comment", "# health_check_path:"},
	}

	for _, check := range checks {
		t.Run(check.name, func(t *testing.T) {
			if !strings.Contains(yaml, check.contains) {
				t.Errorf("YAML should contain %q", check.contains)
			}
		})
	}
}

func TestHaloyConfig_MarshalYAMLWithComments_NoEnvVars(t *testing.T) {
	config := &HaloyConfig{
		Name:   "test-app",
		Server: "api.example.com",
		Port:   "3000",
		Image: &ImageConfig{
			Repository: "test-app",
			Build:      true,
		},
		Env: nil,
	}

	data, err := config.MarshalYAMLWithComments()
	if err != nil {
		t.Fatalf("MarshalYAMLWithComments() error = %v", err)
	}

	yaml := string(data)

	// Should have commented env example when no env vars
	if !strings.Contains(yaml, "# env:") {
		t.Error("YAML should contain commented '# env:' when no env vars")
	}
	if !strings.Contains(yaml, "#   - name: DATABASE_URL") {
		t.Error("YAML should contain commented env var example")
	}
}
